### ISSUE TITLE
an error with running code

### ISSUE THREAD

**Issue by corookie** [hsaafan/TEPImport#3]
Dear hsaafan,

I tried running your code in Jupyter Notebook using Chrome, but I encountered an issue. It gave me an error message that said, "webdriver got an unexpected keyword argument 'firefox_profile'." Since I'm using Chrome, I would like to know how to run the code in Chrome without encountering this error.

The specific error occurs at the following line in the code:

driver = webdriver.Firefox(options=options,
firefox_profile=profile,
executable_path=GeckoDriverManager().install())

Your guidance on how to adapt this code to work with Chrome would be greatly appreciated.

Thank you for your assistance.

Best regards,
[corookie]

**Comment by hsaafan** [comment]
Hi corookie, the code snippet you posted looks like it's coming from the Selenium package. This package does not use selenium so it might be an issue with some other package you're using.

As a side note though, I don't think it matters that you're running it on Chrome as Selenium essentially installs all the required files for you and runs it's own web browser.
